on:
  push:
    branches:
      - master
  pull_request:
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23.0"
      - name: Download Modules
        run: go mod download
      - name: Run tests
        run: go test -v -covermode=atomic
